<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="Microsoft.Windows.SDK.NET.Ref" />-->
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" PrivateAssets="all" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Diagnostics" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Seq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AluLab.Board\AluLab.Board.csproj" />
    <ProjectReference Include="..\AluLab.Common\AluLab.Common.csproj" />
  </ItemGroup>
</Project>
