<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Linux -->
    <OutputType>Exe</OutputType>
    <PublishTrimmed>false</PublishTrimmed>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!-- Raspberry Pi 4B (64-bit OS) -->
  <!-- Only set a RID when explicitly publishing or when one is already provided -->
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == '' and '$(IsPublish)' == 'true'">
    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Diagnostics" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Seq" />    
  </ItemGroup>

  <ItemGroup><!--<PackageReference Include="SkiaSharp.NativeAssets.Linux" />-->
  
    <AvaloniaXaml Remove="publish-test\**" />
    <Compile Remove="publish-test\**" />
    <EmbeddedResource Remove="publish-test\**" />
    <None Remove="publish-test\**" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\AluLab.Board\AluLab.Board.csproj" />
    <ProjectReference Include="..\AluLab.Common\AluLab.Common.csproj" />
  </ItemGroup>

</Project>